// ESLint flat config (ESLint 9). Mirrors the modern Vite + React + TS
// starter: typescript-eslint recommended, react-hooks recommended, and
// react-refresh for HMR-safe component exports.
//
// `src/api/gen.ts` is generated by openapi-typescript and is excluded
// from linting; if it ever fails, fix the upstream OpenAPI spec, not
// the generated file.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "dist",
      "node_modules",
      "src/api/gen.ts",
      "playwright-report",
      "test-results",
      "e2e/test-results",
      "coverage",
      "*.tsbuildinfo",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Project-wide TS rules. Honor the universal `_`-prefix convention
    // for intentionally unused parameters / variables — the default rule
    // rejects them outright, which clashes with required callback
    // signatures (e.g. Playwright `globalSetup(config)`, reducer `(qc, e)`
    // tables).
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser, ...globals.es2022 },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // React-only rules: applied to the app source. The e2e Playwright
    // suite is browser-driving Node code; it doesn't import React and
    // its `use(value)` fixture API trips react-hooks/rules-of-hooks.
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      react,
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
    settings: { react: { version: "18.3" } },
  },
  {
    // Node-environment files (build config, test setup, playwright config).
    files: ["vite.config.ts", "playwright.config.ts", "e2e/**/*.ts", "src/test/setup.ts"],
    languageOptions: {
      globals: { ...globals.node, ...globals.es2022 },
    },
  },
  {
    // Playwright fixture API: `({}, use) => ...` is the documented shape
    // for a no-dependency fixture (empty object destructure communicates
    // "no other fixtures needed"). The default `no-empty-pattern` rule
    // can't tell this from a coding mistake.
    files: ["e2e/**/*.ts"],
    rules: {
      "no-empty-pattern": "off",
    },
  },
  {
    // Vitest unit tests run in jsdom but reach for vitest globals.
    files: ["src/**/*.{test,spec}.{ts,tsx}"],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
);
