/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs. */
        get: operations["listRuns"];
        put?: never;
        /**
         * Submit a DAG.
         * @description Accept a new DAG, validate it, persist it, set initial state.
         *     Idempotent on the submission `id`: re-submitting the same id returns
         *     `409 DUPLICATE_RESOURCE` with the existing run in `details.current_state`.
         */
        post: operations["submitRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run with its deck_jobs and recent events. */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a run (cascade).
         * @description Sets `runs.status = CANCELLED`; transitions every deck_job not already
         *     terminal to `CANCELLED`. Best-effort abort signal is dialed for any
         *     DISPATCHED/RUNNING job. See `DESIGN.md`.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a FAILED deck_job.
         * @description Transitions a FAILED `deck_job` back to `READY`. A new `attempt_id` is
         *     allocated later by the Dispatcher on the subsequent `READY → DISPATCHED`
         *     transition. See `DESIGN.md`.
         */
        post: operations["retryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/jobs/{job_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve an AMBIGUOUS deck_job to COMPLETED or FAILED.
         * @description Transitions an `AMBIGUOUS` `deck_job` to `COMPLETED` or `FAILED`,
         *     recording the operator's determination on the attempt (with
         *     `outcome_source = OPERATOR_RESOLUTION`). See `DESIGN.md`.
         */
        post: operations["resolveJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet view of decks with current health and current job. */
        get: operations["listDecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decks/{deck_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release a slot back to EMPTY.
         * @description Operator-deliberate vacate: clears `endpoint_url` and
         *     `last_heartbeat_at`, sets `last_known_health = EMPTY`, emits
         *     `DECK_HEALTH_CHANGED` if the prior state was non-EMPTY.
         *     Idempotent on already-EMPTY slots. Refuses with
         *     `409 SLOT_HAS_INFLIGHT_WORK` when any deck_job in
         *     `DISPATCHED` / `RUNNING` / `AMBIGUOUS` references the slot --
         *     the operator must resolve in-flight work first so released
         *     attempts aren't silently abandoned.
         *
         *     Wired by the supervisor's detach path so a deliberate "remove
         *     executor" round-trips to EMPTY instead of aging through
         *     STALE -> UNREACHABLE. UNREACHABLE then unambiguously means
         *     "executor crashed without operator action," restoring the
         *     rubric's commitment to operator-visible state.
         */
        post: operations["releaseDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executor/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Short-poll for the next dispatch for a deck.
         * @description Returns `200` immediately if there is a `DISPATCHED` deck_job
         *     for this deck whose attempt is not yet committed locally;
         *     otherwise returns `204` immediately. The executor calls this on
         *     a fixed `PollInterval` (default 500ms) and uses `INSERT OR
         *     IGNORE` on `attempt_id` to dedupe redelivery across orchestrator
         *     restarts. Short-poll over long-poll: simpler, no held subscriber
         *     state across restarts, fine at the assignment's 100-deck scale.
         */
        get: operations["executorPoll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executor/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deliver an executor state event.
         * @description Idempotent on `(attempt_id, kind)`. The handler returns `200` for all
         *     of "applied", "duplicate", and "conflict_logged" — the response body's
         *     `status` field distinguishes them so the executor's outbox stops
         *     retrying on any 2xx. See `docs/API.md` §9.2.
         */
        post: operations["executorEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executor/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heartbeat with current claim and reachable endpoint URL.
         * @description Fire-and-forget per `DESIGN.md`. Updates the deck
         *     row's endpoint_url + last_heartbeat_at; on the first heartbeat
         *     after the slot was EMPTY emits `DECK_REGISTERED`; on a health
         *     transition emits `DECK_HEALTH_CHANGED`. The orchestrator classifies
         *     health, the executor does not self-report.
         *
         *     Slot identity is fleet-bound: the orchestrator seeds N deck slots
         *     from `fleet_size` at boot, and heartbeats for ids outside that
         *     set are rejected with 404. Decommissioned slots reject heartbeats
         *     with 410. The executor binary treats both as fatal config errors
         *     and exits with code 78 to avoid a respawn loop.
         */
        post: operations["executorHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executor/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Executor-hosted) Authoritative state for an attempt, or overall.
         * @description Dialed by the orchestrator's Reconciler on suspicion of drift. When
         *     `attempt_id` is omitted, returns the executor's overall claim and
         *     recent attempts. See `docs/API.md` §9.4.
         */
        get: operations["executorGetState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executor/abort/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * (Executor-hosted) Best-effort abort signal for an in-flight attempt.
         * @description Dialed by the orchestrator on operator cancel. The executor sets
         *     `attempts.abort_requested` and returns immediately. See `docs/API.md` §9.5.
         */
        post: operations["executorAbort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decks/{deck_id}/chaos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current chaos state for a deck.
         * @description Orchestrator proxies the request to the deck's executor (looked up
         *     via `decks.endpoint_url`). Returns whatever runtime failure-injection
         *     flags are currently set on the executor.
         */
        get: operations["getDeckChaos"];
        put?: never;
        /**
         * Merge a chaos patch into a deck's runtime state.
         * @description Body is a patch — missing fields leave the corresponding flag
         *     untouched, present fields overwrite. To explicitly disable a
         *     step-aware arm, send the field with value `0`.
         */
        post: operations["patchDeckChaos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decks/{deck_id}/chaos/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear every chaos flag on a deck. */
        post: operations["resetDeckChaos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decks/{deck_id}/chaos/crash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One-shot executor crash (os.Exit on the deck process).
         * @description The executor writes a 200 response then exits. Recovery depends on
         *     whatever supervisor is running the executor (the demo script
         *     respawns it; production would use systemd or similar).
         */
        post: operations["crashDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gracefully exit the orchestrator process.
         * @description The orchestrator writes a 202 response, flushes, then calls
         *     `os.Exit(0)` after a brief delay. A supervisor (systemd, the
         *     demo script, etc.) is responsible for relaunching it. Used by
         *     the UI's "Restart orchestrator" button to demonstrate
         *     ARCHITECTURE.md §5.4 scenario 1 (orchestrator restart + startup
         *     reconcile).
         */
        post: operations["restartOrchestrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap or delta-poll the global console state.
         * @description Returns a full snapshot (`runs`, `decks`, recent `events`,
         *     `server_seq`) when `since_seq` is 0 or absent. Returns only
         *     events with `seq > since_seq` otherwise. The client uses
         *     `server_seq` from each response as the next request's
         *     `since_seq`. Gap detection (event seq != last+1) and unknown
         *     event kinds prompt a re-bootstrap by resetting `since_seq` to 0.
         *
         *     Drives the live React console: a single 1-second poll replaces
         *     the per-resource refetch hooks the early prototype used.
         */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap or delta-poll a run-detail screen.
         * @description Same pattern as `GET /api/state` but scoped to one run: the
         *     snapshot carries the full `Run` (with recent attempts) and
         *     only the events that touch that run. Used by the run-detail
         *     screen so the global fleet payload is not re-sent on every
         *     tick.
         */
        get: operations["getRunState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Materialized run status. Terminal statuses are `COMPLETED` (all
         *     deck_jobs succeeded) and `CANCELLED` (operator cut the run).
         *
         *     `FAILED` and `AMBIGUOUS` are non-terminal: the run is awaiting an
         *     operator decision (retry / resolve, or cancel). `terminal_at` is
         *     only stamped on terminal statuses; for FAILED / AMBIGUOUS it is
         *     null until the operator either resumes the run (retry / resolve)
         *     or terminalizes it via cancel. See DESIGN.md.
         * @enum {string}
         */
        RunStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "AMBIGUOUS" | "CANCELLED";
        /**
         * @description deck_job state. See `DESIGN.md`.
         * @enum {string}
         */
        DeckJobStatus: "PENDING" | "READY" | "DISPATCHED" | "RUNNING" | "COMPLETED" | "FAILED" | "AMBIGUOUS" | "CANCELLED";
        /**
         * @description Materialized deck health classification (orchestrator-side).
         *     `EMPTY` is the steady state of a fleet slot that has never been
         *     attached, or whose executor has detached and the orchestrator's
         *     liveness sweep has cleared its endpoint/heartbeat scalars.
         * @enum {string}
         */
        DeckHealth: "EMPTY" | "HEALTHY" | "STALE" | "UNREACHABLE";
        /**
         * @description Authority that determined an attempt's terminal outcome.
         * @enum {string}
         */
        OutcomeSource: "EXECUTOR_EVENT" | "RECONCILE" | "OPERATOR_RESOLUTION";
        /**
         * @description Terminal outcome stamped on `job_attempts`. Deliberately excludes
         *     AMBIGUOUS and CANCELLED — those are deck_job states, not attempt
         *     outcomes (see `DESIGN.md`).
         * @enum {string}
         */
        AttemptOutcome: "COMPLETED" | "FAILED";
        /**
         * @description Closed enum of error codes. Used as the discriminator on `Error`.
         * @enum {string}
         */
        ErrorCode: "INVALID_JSON" | "SCHEMA_VIOLATION" | "MISSING_VERSION" | "INVALID_RESOLUTION" | "RUN_NOT_FOUND" | "JOB_NOT_FOUND" | "UNKNOWN_ATTEMPT" | "DECK_NOT_FOUND" | "DECK_DECOMMISSIONED" | "EXECUTOR_UNREACHABLE" | "VERSION_MISMATCH" | "DUPLICATE_RESOURCE" | "ALREADY_TERMINAL" | "INVALID_TRANSITION" | "DAG_VALIDATION_FAILED" | "PAYLOAD_TOO_LARGE" | "INTERNAL_ERROR" | "DEGRADED_MODE" | "SLOT_HAS_INFLIGHT_WORK";
        /**
         * @description Inner code in a `DAG_VALIDATION_FAILED.details.errors[]` entry.
         *     `DECK_DECOMMISSIONED` is reserved for decks that exist in the
         *     fleet but have been retired; `UNKNOWN_DECK` is for ids outside
         *     the configured fleet entirely.
         * @enum {string}
         */
        DagValidationCode: "DAG_HAS_NO_JOBS" | "DUPLICATE_JOB_ID" | "JOB_HAS_NO_STEPS" | "UNKNOWN_DECK" | "DECK_DECOMMISSIONED" | "UNKNOWN_DEPENDENCY" | "DAG_HAS_CYCLE";
        /**
         * @description Kinds the executor delivers via POST /executor/events.
         *     STEP_COMPLETED is a scalar progress update (no state-machine transition);
         *     the orchestrator applies a monotonic UPDATE to deck_jobs.last_completed_step
         *     and appends a JOB_STEP_COMPLETED event for the operator surface.
         *     Payload for STEP_COMPLETED: `{"step": <1-indexed int>, "total": <int>}`.
         * @enum {string}
         */
        ExecutorEventKind: "RUNNING" | "COMPLETED" | "FAILED" | "STEP_COMPLETED";
        /**
         * @description Closed enum of orchestrator-side event kinds written to the
         *     `events` table. The set mirrors `backend/internal/eventlog/kinds.go`
         *     and `STATE_MACHINE.md` §10 (the event taxonomy). Frontend reducers
         *     in `lib/live/reducers/` are indexed on these values.
         * @enum {string}
         */
        EventKind: "RUN_SUBMITTED" | "RUN_STATUS_CHANGED" | "JOB_READY" | "JOB_DISPATCHED" | "JOB_RUNNING" | "JOB_STEP_COMPLETED" | "JOB_COMPLETED" | "JOB_FAILED" | "JOB_AMBIGUOUS" | "JOB_CANCELLED" | "JOB_RESOLVED" | "JOB_RETRIED" | "DECK_REGISTERED" | "DECK_HEALTH_CHANGED" | "EXECUTOR_CONFLICT_LOGGED";
        /**
         * @description Executor-side attempt state. See `DESIGN.md`.
         * @enum {string}
         */
        ExecutorAttemptState: "RECEIVED" | "IN_PROGRESS" | "COMPLETED" | "FAILED";
        Step: {
            type: string;
            description: string;
        };
        /**
         * @description One row of `job_attempts`. See `DESIGN.md`.
         *
         *     Nullability: `outcome`/`outcome_at`/`outcome_source` are null while
         *     the attempt is still in flight; they are set together (per the
         *     all-or-nothing CHECK on the storage row) when the attempt reaches a
         *     terminal answer. `result` is populated only on COMPLETED via an
         *     executor event; `error` only on FAILED.
         */
        JobAttempt: {
            /** Format: uuid */
            attempt_id: string;
            /** Format: date-time */
            dispatched_at: string;
            outcome?: components["schemas"]["AttemptOutcome"] | null;
            /** Format: date-time */
            outcome_at?: string | null;
            outcome_source?: components["schemas"]["OutcomeSource"] | null;
            /** @description Executor-reported result payload (opaque). */
            result?: {
                [key: string]: unknown;
            } | null;
            error?: string | null;
            operator_note?: string | null;
        };
        /** @description A deck_job row plus recent attempts. See `DESIGN.md`. */
        DeckJob: {
            id: string;
            deck_id: string;
            depends_on: string[];
            steps: components["schemas"]["Step"][];
            status: components["schemas"]["DeckJobStatus"];
            /** Format: uuid */
            current_attempt_id?: string | null;
            /** Format: int64 */
            version: number;
            error?: string | null;
            /**
             * Format: int64
             * @description Bootstrap denormalization of the most recent committed step cursor.
             *     0 means no steps have completed (job not yet running or just dispatched).
             *     Updated by the orchestrator each time it receives a STEP_COMPLETED
             *     executor event; also set to `total_steps` when a COMPLETED event lands
             *     so the UI never shows a partial count on a finished job.
             */
            last_completed_step?: number;
            /**
             * Format: int64
             * @description Total number of steps in this deck_job. Set at submit time from
             *     `len(deck_job.steps)`. Combined with `last_completed_step` this
             *     allows the UI to render "step 2/5" without replaying the event log.
             */
            total_steps?: number;
            /**
             * @description Set when status is AMBIGUOUS, identifying which liveness path
             *     declared the attempt unreachable: DEADLINE_EXCEEDED (the
             *     orchestrator's per-attempt hang ceiling fired and the executor
             *     still reported IN_PROGRESS), DEADLINE_ELAPSED (the deck went
             *     UNREACHABLE and the AmbiguousDeadline expired with no
             *     authoritative outcome), or EXECUTOR_REPORTED_UNKNOWN (the
             *     executor explicitly said it lost track of the attempt).
             *     Cleared (null) when the operator resolves or retries.
             * @enum {string|null}
             */
            ambiguous_reason?: "DEADLINE_ELAPSED" | "EXECUTOR_REPORTED_UNKNOWN" | "DEADLINE_EXCEEDED" | null;
            /** @description Newest first. Only present on `GET /api/runs/{id}` responses. */
            recent_attempts?: components["schemas"]["JobAttempt"][];
        };
        /** @description Aggregate counts of deck_jobs by status in a run. */
        DeckJobsSummary: {
            total: number;
            /** @description Map of `DeckJobStatus` to count. Statuses with zero count may be omitted. */
            by_status: {
                [key: string]: number;
            };
        };
        /** @description The deck_job currently occupying a deck's slot. Null when the deck is idle. */
        CurrentJob: {
            run_id: string;
            job_id: string;
            status: components["schemas"]["DeckJobStatus"];
        };
        /**
         * @description Fleet view row. See `DESIGN.md`. With the
         *     decks-as-slots model, `endpoint_url` and `last_heartbeat_at` are
         *     nullable: a slot that has never been attached (or whose executor
         *     has been detached long enough for the liveness sweep to clear
         *     its scalars) has neither, and reports `last_known_health = EMPTY`.
         *     `decommissioned_at` is non-null only for retired slots; the
         *     operator-facing fleet view filters them out by default.
         */
        Deck: {
            id: string;
            /** Format: date-time */
            first_seen_at: string;
            /** Format: date-time */
            last_heartbeat_at?: string | null;
            last_known_health: components["schemas"]["DeckHealth"];
            /** Format: uuid */
            last_claimed_attempt_id?: string | null;
            /**
             * @description The advertise URL the orchestrator dials for /executor/state
             *     and /executor/abort. Populated on first heartbeat; nullable
             *     until then (empty slot) and cleared by long-detach aging.
             */
            endpoint_url?: string | null;
            /**
             * Format: date-time
             * @description Operator-set retirement timestamp. Decommissioned slots are
             *     hidden from the default fleet listing and reject heartbeats
             *     with 410 Gone.
             */
            decommissioned_at?: string | null;
            current_job?: components["schemas"]["CurrentJob"] | null;
        };
        /** @description A deck_job as submitted by the operator (no server-added fields). */
        DagJobSubmission: {
            id: string;
            deck_id: string;
            depends_on: string[];
            steps: components["schemas"]["Step"][];
        };
        /** @description The DAG payload an operator submits to `POST /api/runs`. */
        DagSubmission: {
            id: string;
            deck_jobs: components["schemas"]["DagJobSubmission"][];
        };
        /** @description List-view shape (omits `dag` and per-job `steps`). */
        RunSummary: {
            id: string;
            status: components["schemas"]["RunStatus"];
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            submitted_at: string;
            /**
             * Format: date-time
             * @description Stamped only when the run reaches a terminal status (`COMPLETED`
             *     or `CANCELLED`). Null while in `PENDING`, `RUNNING`, `FAILED`,
             *     or `AMBIGUOUS` — including FAILED runs that are awaiting an
             *     operator decision.
             */
            terminal_at?: string | null;
            deck_jobs_summary: components["schemas"]["DeckJobsSummary"];
        };
        /** @description Run detail. Same shape returned by `POST /api/runs` and operator mutations. */
        Run: {
            id: string;
            status: components["schemas"]["RunStatus"];
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            submitted_at: string;
            /**
             * Format: date-time
             * @description Stamped only when the run reaches a terminal status (`COMPLETED`
             *     or `CANCELLED`). Null while in `PENDING`, `RUNNING`, `FAILED`,
             *     or `AMBIGUOUS` — including FAILED runs that are awaiting an
             *     operator decision.
             */
            terminal_at?: string | null;
            dag: components["schemas"]["DagSubmission"];
            deck_jobs: components["schemas"]["DeckJob"][];
        };
        /**
         * @description One row of the orchestrator's `events` audit table, serialized
         *     for the live polling surface. `payload` is kind-dependent; see
         *     `backend/internal/eventlog/payloads.go` for shapes (callers
         *     should generally key off `kind` + scope fields and treat
         *     payload as advisory).
         */
        Event: {
            /**
             * Format: int64
             * @description Monotonically increasing event sequence (DB primary key).
             */
            seq: number;
            /**
             * Format: date-time
             * @description Orchestrator-stamped wall clock.
             */
            occurred_at: string;
            kind: components["schemas"]["EventKind"];
            run_id?: string | null;
            job_id?: string | null;
            deck_id?: string | null;
            /** Format: uuid */
            attempt_id?: string | null;
            /** @description Kind-specific extras. Empty object when there are none. */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Response for `GET /api/state`. When `since_seq=0` (bootstrap)
         *     `runs` and `decks` are populated with the current fleet view;
         *     in steady state (`since_seq > 0`) `decks` is omitted and
         *     `decks_delta` carries only the touched-since slice. `server_seq`
         *     is the highest event seq known to the orchestrator at response
         *     time — clients use it as the next request's `since_seq`.
         */
        StateSnapshot: {
            /** Format: int64 */
            server_seq: number;
            events: components["schemas"]["Event"][];
            /** @description Bootstrap-only. Omitted from delta responses. */
            runs?: components["schemas"]["RunSummary"][];
            /**
             * @description Bootstrap-only authoritative slice for every deck. Omitted
             *     from delta responses (since_seq > 0); use `decks_delta` there.
             */
            decks?: components["schemas"]["Deck"][];
            /**
             * @description Delta-only. Decks whose row was touched since `since_seq`:
             *     union of (a) decks referenced by any event with seq >
             *     since_seq and (b) decks whose `last_heartbeat_at` advanced
             *     inside the recent freshness window (orchestrator-chosen,
             *     currently 5s). Clients merge by `id` into the existing
             *     decks cache instead of replacing wholesale. Bounds steady
             *     poll cost by activity rather than fleet size (see S3 in
             *     analysis/inefficiencies/inefficiencies.md).
             */
            decks_delta?: components["schemas"]["Deck"][];
        };
        /**
         * @description Response for `GET /api/runs/{id}/state`. Same semantics as
         *     `StateSnapshot` but scoped to one run; `events` only includes
         *     rows whose `run_id` matches. `run` is populated on bootstrap.
         */
        RunStateSnapshot: {
            /** Format: int64 */
            server_seq: number;
            events: components["schemas"]["Event"][];
            /** @description Bootstrap-only. Omitted from delta responses. */
            run?: components["schemas"]["Run"] | null;
        };
        CancelRunRequest: {
            /** Format: int64 */
            expected_version: number;
        };
        RetryJobRequest: {
            /** Format: int64 */
            expected_version: number;
        };
        ResolveJobRequest: {
            /** Format: int64 */
            expected_version: number;
            resolution: components["schemas"]["AttemptOutcome"];
            /** @description Optional free-text note. Recommended for FAILED resolutions. */
            operator_note?: string;
        };
        /** @description Response from a successful `GET /executor/poll`. */
        DispatchPayload: {
            /** Format: uuid */
            attempt_id: string;
            run_id: string;
            job_id: string;
            steps: components["schemas"]["Step"][];
        };
        ExecutorEventRequest: {
            /** Format: uuid */
            attempt_id: string;
            kind: components["schemas"]["ExecutorEventKind"];
            /**
             * Format: date-time
             * @description Executor wall-clock. Advisory; orchestrator stamps its own server-side time.
             */
            occurred_at: string;
            /**
             * @description Optional kind-specific payload.
             *     For COMPLETED: `{"result": {...}}`.
             *     For FAILED: `{"error": "..."}`.
             *     For RUNNING: typically absent or empty.
             *     For STEP_COMPLETED: `{"step": <1-indexed int>, "total": <int>}`.
             *       The orchestrator applies a monotonic MAX update to
             *       deck_jobs.last_completed_step and appends JOB_STEP_COMPLETED
             *       to the event log. No state-machine transition; job stays RUNNING.
             */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Discriminator on `ExecutorEventResponse`.
         * @enum {string}
         */
        ExecutorEventStatus: "applied" | "duplicate" | "conflict_logged";
        /**
         * @description The state transition was applied. Returned when the incoming
         *     `(attempt_id, kind)` had no recorded outcome yet.
         */
        ExecutorEventApplied: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "applied";
            new_job_status: components["schemas"]["DeckJobStatus"];
            /** Format: int64 */
            new_job_version: number;
        };
        /**
         * @description The orchestrator already had the same `(attempt_id, kind)` outcome
         *     recorded; the incoming event matches. The executor's outbox treats
         *     this as success and stops retrying.
         */
        ExecutorEventDuplicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "duplicate";
            current_outcome: components["schemas"]["AttemptOutcome"] | null;
            current_outcome_source: components["schemas"]["OutcomeSource"] | null;
        };
        /**
         * @description The orchestrator had a different outcome already recorded (or the
         *     deck_job has been CANCELLED). The conflict is logged as an
         *     `EXECUTOR_CONFLICT_LOGGED` event; no state transition occurs. The
         *     executor's outbox stops retrying.
         */
        ExecutorEventConflictLogged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "conflict_logged";
            /** @description Null when the conflict is against a CANCELLED deck_job that never had an attempt outcome. */
            current_outcome: components["schemas"]["AttemptOutcome"] | null;
            current_outcome_source: components["schemas"]["OutcomeSource"] | null;
            your_reported_outcome: components["schemas"]["ExecutorEventKind"];
            /** @description Populated when the conflict source is a cancelled deck_job (e.g., `CANCELLED`). Optional otherwise. */
            current_job_status?: components["schemas"]["DeckJobStatus"];
        };
        /** @description Discriminated union over the three response shapes of POST /executor/events. */
        ExecutorEventResponse: components["schemas"]["ExecutorEventApplied"] | components["schemas"]["ExecutorEventDuplicate"] | components["schemas"]["ExecutorEventConflictLogged"];
        Heartbeat: {
            deck_id: string;
            /** Format: uuid */
            current_attempt_id?: string | null;
            /**
             * Format: uri
             * @description URL the orchestrator dials for `/executor/state` and `/executor/abort/{attempt_id}`.
             */
            endpoint_url: string;
        };
        ExecutorStateAttempt: {
            /** Format: uuid */
            attempt_id: string;
            state: components["schemas"]["ExecutorAttemptState"];
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            terminal_at?: string | null;
            result?: {
                [key: string]: unknown;
            } | null;
            error?: string | null;
        };
        ExecutorStateOverall: {
            deck_id: string;
            /** Format: uuid */
            current_attempt_id?: string | null;
            current_state?: components["schemas"]["ExecutorAttemptState"] | null;
            recent_attempts: components["schemas"]["ExecutorStateAttempt"][];
        };
        /**
         * @description Either a per-attempt state (when called with `attempt_id`) or an
         *     overall executor state (when called without).
         */
        ExecutorStateResponse: components["schemas"]["ExecutorStateAttempt"] | components["schemas"]["ExecutorStateOverall"];
        /** @enum {string} */
        AbortStatus: "abort_requested" | "already_terminal";
        AbortResponse: {
            status: components["schemas"]["AbortStatus"];
            /** Format: uuid */
            attempt_id: string;
            final_state?: components["schemas"]["ExecutorAttemptState"];
        };
        /**
         * @description Complete view of an executor's runtime chaos flags. Returned by
         *     `GET /api/decks/{deck_id}/chaos` and as the success response of
         *     every chaos mutation.
         */
        ChaosState: {
            /** @description Worker blocks at next step boundary while true. */
            hang: boolean;
            /**
             * @description Armed: the worker promotes the immediate-hang toggle to true
             *     after completing step N. Zero disables.
             */
            hang_after_step: number;
            /**
             * @description Armed: the worker invokes the crash callback after completing
             *     step N. Zero disables.
             */
            crash_after_step: number;
            /** @description Worker suppresses heartbeats while true. */
            silent: boolean;
            /** @description Outbox flusher pretends every delivery failed while true. */
            drop_events: boolean;
            /** @description Executor -> orchestrator HTTP returns immediate errors while true. */
            pause_egress: boolean;
            /** @description Orchestrator -> executor HTTP connections are dropped while true (except /executor/chaos and /health, which always answer). */
            pause_ingress: boolean;
        };
        /**
         * @description Partial update to a deck's chaos state. Missing fields leave the
         *     corresponding flag untouched; present fields overwrite. Every
         *     field is optional but at least one is expected.
         */
        ChaosPatch: {
            hang?: boolean;
            hang_after_step?: number;
            crash_after_step?: number;
            silent?: boolean;
            drop_events?: boolean;
            pause_egress?: boolean;
            pause_ingress?: boolean;
        };
        /**
         * @description Common error fields. `request_id` is always present (set by the
         *     request-id middleware on every inbound request); absence indicates
         *     a server bug, not a wire variant.
         */
        ErrorBase: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            request_id: string;
        };
        InvalidJsonError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "INVALID_JSON";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "INVALID_JSON";
        };
        SchemaViolationError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "SCHEMA_VIOLATION";
            details?: {
                [key: string]: unknown;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "SCHEMA_VIOLATION";
        };
        MissingVersionError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "MISSING_VERSION";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "MISSING_VERSION";
        };
        InvalidResolutionError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "INVALID_RESOLUTION";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "INVALID_RESOLUTION";
        };
        RunNotFoundError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "RUN_NOT_FOUND";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "RUN_NOT_FOUND";
        };
        JobNotFoundError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "JOB_NOT_FOUND";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "JOB_NOT_FOUND";
        };
        UnknownAttemptError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "UNKNOWN_ATTEMPT";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "UNKNOWN_ATTEMPT";
        };
        VersionMismatchError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "VERSION_MISMATCH";
            details: {
                /** Format: int64 */
                current_version: number;
                current_state: components["schemas"]["Run"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "VERSION_MISMATCH";
        };
        DuplicateResourceError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "DUPLICATE_RESOURCE";
            details: {
                current_state: components["schemas"]["Run"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "DUPLICATE_RESOURCE";
        };
        AlreadyTerminalError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "ALREADY_TERMINAL";
            details: {
                current_status: components["schemas"]["RunStatus"];
                current_state: components["schemas"]["Run"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "ALREADY_TERMINAL";
        };
        InvalidTransitionError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "INVALID_TRANSITION";
            details: {
                current_status: components["schemas"]["DeckJobStatus"];
                current_state: components["schemas"]["Run"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "INVALID_TRANSITION";
        };
        DagHasNoJobsDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "DAG_HAS_NO_JOBS";
        };
        DuplicateJobIdDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "DUPLICATE_JOB_ID";
            job_id: string;
        };
        JobHasNoStepsDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "JOB_HAS_NO_STEPS";
            job_id: string;
        };
        UnknownDeckDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "UNKNOWN_DECK";
            job_id: string;
            deck_id: string;
        };
        /**
         * @description Submission targets a deck that exists in the fleet but has been
         *     decommissioned. Distinct from UNKNOWN_DECK so the UI can offer
         *     a "revive decommissioned slot" affordance instead of "fix typo".
         */
        DeckDecommissionedDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "DECK_DECOMMISSIONED";
            job_id: string;
            deck_id: string;
        };
        UnknownDependencyDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "UNKNOWN_DEPENDENCY";
            job_id: string;
            missing_dependency: string;
        };
        DagHasCycleDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "DAG_HAS_CYCLE";
            cycle_path: string[];
        };
        /**
         * @description Discriminated union of inner-error shapes inside
         *     `DAG_VALIDATION_FAILED.details.errors[]`. The shape varies per inner
         *     `code`; the UI can render kind-specific copy without parsing
         *     free-form JSON.
         */
        DagValidationFailedDetailEntry: components["schemas"]["DagHasNoJobsDetail"] | components["schemas"]["DuplicateJobIdDetail"] | components["schemas"]["JobHasNoStepsDetail"] | components["schemas"]["UnknownDeckDetail"] | components["schemas"]["DeckDecommissionedDetail"] | components["schemas"]["UnknownDependencyDetail"] | components["schemas"]["DagHasCycleDetail"];
        DagValidationFailedError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "DAG_VALIDATION_FAILED";
            details: {
                errors: components["schemas"]["DagValidationFailedDetailEntry"][];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "DAG_VALIDATION_FAILED";
        };
        PayloadTooLargeError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "PAYLOAD_TOO_LARGE";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "PAYLOAD_TOO_LARGE";
        };
        InternalError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "INTERNAL_ERROR";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "INTERNAL_ERROR";
        };
        DegradedModeError: components["schemas"]["ErrorBase"] & {
            /** @enum {string} */
            code: "DEGRADED_MODE";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            code: "DEGRADED_MODE";
        };
        /** @description Discriminated union over all error codes. */
        Error: components["schemas"]["InvalidJsonError"] | components["schemas"]["SchemaViolationError"] | components["schemas"]["MissingVersionError"] | components["schemas"]["InvalidResolutionError"] | components["schemas"]["RunNotFoundError"] | components["schemas"]["JobNotFoundError"] | components["schemas"]["UnknownAttemptError"] | components["schemas"]["VersionMismatchError"] | components["schemas"]["DuplicateResourceError"] | components["schemas"]["AlreadyTerminalError"] | components["schemas"]["InvalidTransitionError"] | components["schemas"]["DagValidationFailedError"] | components["schemas"]["PayloadTooLargeError"] | components["schemas"]["InternalError"] | components["schemas"]["DegradedModeError"];
        /** @description Outer envelope wrapping every non-2xx response. */
        ErrorResponse: {
            error: components["schemas"]["Error"];
        };
    };
    responses: {
        /** @description Unhandled server error. */
        InternalErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Orchestrator in degraded mode; mutations refused. */
        DegradedModeResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        RunId: string;
        JobId: string;
        DeckId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRuns: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs: components["schemas"]["RunSummary"][];
                    };
                };
            };
            /** @description Bad query parameter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    submitRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DagSubmission"];
            };
        };
        responses: {
            /** @description Run created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Malformed or schema-invalid request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Duplicate id. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request body exceeds 1 MB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description DAG semantic validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
            503: components["responses"]["DegradedModeResponse"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRunRequest"];
            };
        };
        responses: {
            /** @description Cancelled. Returns the full updated run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Missing version. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Version mismatch or already terminal. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
            503: components["responses"]["DegradedModeResponse"];
        };
    };
    retryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryJobRequest"];
            };
        };
        responses: {
            /** @description Retry queued. Returns the full updated run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Missing version. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run or job not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Version mismatch, invalid transition, or already terminal (parent run). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
            503: components["responses"]["DegradedModeResponse"];
        };
    };
    resolveJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveJobRequest"];
            };
        };
        responses: {
            /** @description Resolved. Returns the full updated run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Missing version or invalid resolution. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Run or job not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Version mismatch or invalid transition. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
            503: components["responses"]["DegradedModeResponse"];
        };
    };
    listDecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Decks list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        decks: components["schemas"]["Deck"][];
                    };
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    releaseDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slot released (or already EMPTY). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Unknown deck_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Slot has in-flight work; resolve before release. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Slot is decommissioned. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    executorPoll: {
        parameters: {
            query: {
                deck_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dispatch ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchPayload"];
                };
            };
            /** @description Long-poll timed out with no work. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    executorEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutorEventRequest"];
            };
        };
        responses: {
            /**
             * @description Event received. The response body is discriminated on `status`:
             *     `applied` (transition recorded), `duplicate` (already recorded,
             *     matching outcome), or `conflict_logged` (already recorded,
             *     different outcome — conflict event written, no state change).
             *     All three are 2xx so the executor outbox stops retrying.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutorEventResponse"];
                };
            };
            /** @description Unknown attempt_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    executorHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Heartbeat"];
            };
        };
        responses: {
            /** @description Heartbeat received. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Heartbeating deck_id is not in this orchestrator's fleet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Heartbeating deck_id was decommissioned by an operator. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    executorGetState: {
        parameters: {
            query?: {
                attempt_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Executor's view (per-attempt or overall). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutorStateResponse"];
                };
            };
            /** @description Unknown attempt_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    executorAbort: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abort flag set or already terminal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbortResponse"];
                };
            };
            /** @description Executor has no record of this attempt_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    getDeckChaos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosState"];
                };
            };
            /** @description Unknown deck_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Executor unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patchDeckChaos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChaosPatch"];
            };
        };
        responses: {
            /** @description Merged state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosState"];
                };
            };
            /** @description Malformed body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown deck_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Executor unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resetDeckChaos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset state (all-zero). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaosState"];
                };
            };
            /** @description Unknown deck_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Executor unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    crashDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: components["parameters"]["DeckId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Crash initiated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "crashing";
                    };
                };
            };
            /** @description Unknown deck_id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Executor unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restartOrchestrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restart accepted; process exit imminent. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "restarting";
                    };
                };
            };
        };
    };
    getState: {
        parameters: {
            query?: {
                since_seq?: number;
                /**
                 * @description Maximum number of events to return in this response.
                 *     Caps to 1000. Clients that see `events.length == limit`
                 *     should poll again immediately (or re-bootstrap if the
                 *     event log has rotated).
                 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description State snapshot or delta. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateSnapshot"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
    getRunState: {
        parameters: {
            query?: {
                since_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run state snapshot or delta. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStateSnapshot"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalErrorResponse"];
        };
    };
}
